---
driver:
  name: docker
  hostname: barbican.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: barbican
  grains:
    noservices: True
  dependencies:
    - name: apache
      repo: git
      source: https://github.com/salt-formulas/salt-formula-apache
  state_top:
    base:
      "*":
        - apache
        - barbican
  pillars:
    top.sls:
      base:
        "*":
          - barbican

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:
  - name: ssl
    provisioner:
      pillars-from-files:
        barbican.sls: tests/pillar/ssl.sls

  - name: control_single
    provisioner:
      pillars-from-files:
        barbican.sls: tests/pillar/control_single.sls

  - name: control_cluster
    provisioner:
      pillars-from-files:
        barbican.sls: tests/pillar/control_cluster.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
